import { Agent, AgentExecutionResult, AgentStatus, CompletionMode } from '@magic-wand/agent-framework';
import { execa } from 'execa';
import fs from 'fs-extra';
import path from 'path';
import { prisma } from '@magic-wand/db';
import { Octokit } from '@octokit/rest';

interface GitHubPusherInput {
  projectId: string;
  codeDirectory: string;
  githubRepoUrl: string;
  githubPat: string;
  commitMessage?: string;
}

interface GitHubPusherOutput {
  pushResult: {
    commitSha: string;
    branch: string;
    repositoryUrl: string;
    filesPushed: number;
  };
}

export class GitHubPusherAgent extends Agent {
  constructor() {
    super({
      agentId: 'github-pusher',
      name: 'GitHub 푸셔',
      role: '생성된 코드를 GitHub 레포지토리에 푸시',
      trigger: {
        type: 'dependency_satisfied',
        dependencies: ['code-generator'],
        condition: 'code_generator.status == "success" OR code_generator.status == "partial"',
      },
      completionMode: CompletionMode.AUTO_CLOSE,
      maxRetries: 3,
      timeout: 300, // 5분
      dependencies: ['code-generator'],
      contextSharing: {
        sharesTo: ['netlify-deployer', 'issue-resolver'],
        data: ['github_commit_sha', 'github_branch'],
      },
    });

    this.gitConfig = {
      userName: 'MAGIC WAND',
      userEmail: 'magic-wand@automation.local',
    };
  }

  private gitConfig: {
    userName: string;
    userEmail: string;
  };

  async execute(input: GitHubPusherInput): Promise<AgentExecutionResult> {
    await this.log('GitHub 푸시 시작', { projectId: input.projectId, repo: input.githubRepoUrl });

    try {
      // 1. GitHub 레포지토리 정보 추출
      const { owner, repo } = this.parseGitHubUrl(input.githubRepoUrl);

      // 2. Octokit 초기화
      const octokit = new Octokit({
        auth: input.githubPat || process.env.GITHUB_PAT,
      });

      // 3. 레포지토리가 없으면 생성 (조직 또는 개인 계정)
      await this.createRepositoryIfNeeded(octokit, owner, repo, input.projectId);

      // 4. Git 초기화
      await this.initializeGit(input.codeDirectory);

      // 5. 레포지토리 연결
      await this.addRemote(input.codeDirectory, input.githubRepoUrl);

      // 6. 파일 커밋
      const filesPushed = await this.commitFiles(input.codeDirectory, input.commitMessage);

      // 7. 푸시
      const pushResult = await this.pushToGitHub(input.codeDirectory, octokit, owner, repo);

      const output: GitHubPusherOutput = {
        pushResult: {
          commitSha: pushResult.commitSha,
          branch: pushResult.branch,
          repositoryUrl: input.githubRepoUrl,
          filesPushed,
        },
      };

      // 8. 데이터베이스 업데이트
      await this.updateDeployment(input.projectId, output);

      await this.log('GitHub 푸시 완료', {
        commitSha: output.pushResult.commitSha,
        filesPushed,
      });

      return {
        status: AgentStatus.COMPLETED,
        output,
      };
    } catch (error: any) {
      await this.logError(error);

      // 재시도 전략
      if (await this.handlePushFailure(input, error)) {
        return this.execute(input);
      }

      return {
        status: AgentStatus.FAILED,
        error: {
          message: error.message,
          stackTrace: error.stack,
          retryable: this.isRetryable(error),
        },
      };
    }
  }

  private parseGitHubUrl(url: string): { owner: string; repo: string } {
    // GitHub URL 파싱
    // 예: https://github.com/owner/repo.git
    // 예: git@github.com:owner/repo.git

    const patterns = [
      /https?:\/\/github\.com\/([^\/]+)\/([^\/]+?)(\.git)?$/,
      /git@github\.com:([^\/]+)\/([^\/]+?)(\.git)?$/,
    ];

    for (const pattern of patterns) {
      const match = url.match(pattern);
      if (match) {
        return { owner: match[1], repo: match[2].replace('.git', '') };
      }
    }

    throw new Error(`Invalid GitHub URL: ${url}`);
  }

  private async initializeGit(cwd: string): Promise<void> {
    // git init
    await execa('git', ['init'], { cwd });

    // git config
    await execa('git', ['config', 'user.name', this.gitConfig.userName], { cwd });
    await execa('git', ['config', 'user.email', this.gitConfig.userEmail], { cwd });
  }

  private async addRemote(cwd: string, url: string): Promise<void> {
    // remote가 이미 있으면 제거
    try {
      await execa('git', ['remote', 'remove', 'origin'], { cwd });
    } catch (error) {
      // remote가 없으면 무시
    }

    // remote 추가
    await execa('git', ['remote', 'add', 'origin', url], { cwd });
  }

  private async commitFiles(cwd: string, commitMessage?: string): Promise<number> {
    const message = commitMessage || 'feat: initial MVP generated by MAGIC WAND 🪄\n\nCo-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>';

    // git add .
    await execa('git', ['add', '.'], { cwd });

    // git commit
    await execa('git', ['commit', '-m', message], { cwd });

    // 파일 수 카운트
    const { stdout } = await execa('git', ['ls-files'], { cwd });
    const files = stdout.trim().split('\n').filter(Boolean);

    return files.length;
  }

  private async pushToGitHub(
    cwd: string,
    octokit: Octokit,
    owner: string,
    repo: string
  ): Promise<{ commitSha: string; branch: string }> {
    const branch = 'main';

    // git push
    await execa('git', ['push', '-u', 'origin', branch], { cwd, timeout: 120000 });

    // 최신 커밋 SHA 가져오기
    const { stdout: sha } = await execa('git', ['rev-parse', 'HEAD'], { cwd });

    return {
      commitSha: sha.trim(),
      branch,
    };
  }

  private async createRepositoryIfNeeded(
    octokit: Octokit,
    owner: string,
    repo: string,
    projectId: string
  ): Promise<void> {
    try {
      await this.log('레포지토리 존재 확인', { owner, repo });

      // 레포지토리 존재 확인
      try {
        await octokit.rest.repos.get({ owner, repo });
        await this.log('레포지토리 이미 존재', { owner, repo });
        return;
      } catch (error: any) {
        if (error.status !== 404) {
          throw error;
        }
        // 404 = 레포지토리 없음, 생성 진행
      }

      await this.log('레포지토리 생성 시작', { owner, repo });

      // 조직(org)인지 개인 사용자인지 확인
      // owner가 orgs/{orgname} 형식이면 조직
      const isOrg = owner.startsWith('orgs/');
      const orgName = isOrg ? owner.replace('orgs/', '') : owner;

      if (isOrg) {
        // 조직 하위에 레포지토리 생성
        await octokit.rest.repos.createInOrg({
          org: orgName,
          name: repo,
          description: `Generated by MAGIC WAND - Project ${projectId}`,
          private: false,
          auto_init: false,
        });
        await this.log('조직 레포지토리 생성 완료', { org: orgName, repo });
      } else {
        // 개인 계정에 레포지토리 생성
        await octokit.rest.repos.createForAuthenticatedUser({
          name: repo,
          description: `Generated by MAGIC WAND - Project ${projectId}`,
          private: false,
          auto_init: false,
        });
        await this.log('개인 레포지토리 생성 완료', { owner, repo });
      }

      // 잠시 대기 (GitHub에서 레포지토리 인덱싱 대기)
      await new Promise(resolve => setTimeout(resolve, 2000));
    } catch (error: any) {
      await this.logError(error);
      throw new Error(`레포지토리 생성 실패: ${error.message}`);
    }
  }

  private async handlePushFailure(input: GitHubPusherInput, error: any): Promise<boolean> {
    const errorMessage = error.message || '';

    // 인증 오류
    if (errorMessage.includes('authentication') || errorMessage.includes('401')) {
      await this.log('인증 실패, PAT 확인 필요', { error: errorMessage });
      return false;
    }

    // 충돌
    if (errorMessage.includes('conflict') || errorMessage.includes('would be overwritten')) {
      await this.log('충돌 발생, 새 브랜치 시도');
      try {
        const newBranch = `magic-wand-${Date.now()}`;
        await execa('git', ['checkout', '-b', newBranch], { cwd: input.codeDirectory });
        await execa('git', ['push', '-u', 'origin', newBranch], { cwd: input.codeDirectory });
        return true;
      } catch (branchError) {
        return false;
      }
    }

    // 네트워크 오류는 재시도
    if (this.isRetryable(error)) {
      return true;
    }

    return false;
  }

  private async updateDeployment(projectId: string, output: GitHubPusherOutput): Promise<void> {
    await prisma.deployment.update({
      where: { projectId },
      data: {
        githubRepoUrl: output.pushResult.repositoryUrl,
        githubBranch: output.pushResult.branch,
        status: 'IN_PROGRESS',
      },
    });
  }
}
